import { NextResponse } from "next/server";

// for fron-end development dummy data

const posts = [
  {
    id: 1,
    name: "Jane Smith",
    username: "janesmith",
    time: "2h",
    ProfileImage: "/images/avatar1.png",
    content: "Just launched my new portfolio! 🚀 #webdesign #portfolio",
    image: "/images/avatar1.png",
    likes: 24,
    comments: 5,
    shares: 2,
    following: false,
  },
  {
    id: 2,
    name: "Alex Johnson",
    username: "alexj",
    time: "4h",
    ProfileImage: "/images/avatar2.png",
    content: "Working on some exciting new features! Stay tuned 👀",
    image: "/images/avatar1.png",
    likes: 10,
    comments: 1,
    shares: 0,
    following: false,
  },
  {
    id: 3,
    name: "Emily Davis",
    username: "emilyd",
    time: "1d",
    ProfileImage: "/images/avatar2.png",
    content: "Designing new UI concepts 💡",
    image: "/images/avatar2.png",
    likes: 40,
    comments: 6,
    shares: 4,
    following: false,
  },
  {
    id: 4,
    name: "Jane Smith",
    username: "janesmith",
    time: "2h",
    ProfileImage: "/images/avatar1.png",
    content: "Just launched my new portfolio! 🚀 #webdesign #portfolio",
    image: "/images/avatar1.png",
    likes: 24,
    comments: 5,
    shares: 2,
    following: false,
  },
  {
    id: 5,
    name: "Alex Johnson",
    username: "alexj",
    time: "4h",
    ProfileImage: "/images/avatar2.png",
    content: "Working on some exciting new features! Stay tuned 👀",
    image: "/images/avatar1.png",
    likes: 10,
    comments: 1,
    shares: 0,
    following: false,
  },
  {
    id: 6,
    name: "Emily Davis",
    username: "emilyd",
    time: "1d",
    ProfileImage: "/images/avatar2.png",
    content: "Designing new UI concepts 💡",
    image: "/images/avatar2.png",
    likes: 40,
    comments: 6,
    shares: 4,
    following: false,
  },
  {
    id: 7,
    name: "Jane Smith",
    username: "janesmith",
    time: "2h",
    ProfileImage: "/images/avatar1.png",
    content: "Just launched my new portfolio! 🚀 #webdesign #portfolio",
    image: "/images/avatar1.png",
    likes: 24,
    comments: 5,
    shares: 2,
    following: true,
  },
  {
    id: 8,
    name: "Alex Johnson",
    username: "alexj",
    time: "4h",
    ProfileImage: "/images/avatar2.png",
    content: "Working on some exciting new features! Stay tuned 👀",
    image: "/images/avatar1.png",
    likes: 10,
    comments: 1,
    shares: 0,
    following: false,
  },
  {
    id: 9,
    name: "Emily Davis",
    username: "emilyd",
    time: "1d",
    ProfileImage: "/images/avatar2.png",
    content: "Designing new UI concepts 💡",
    image: "/images/avatar2.png",
    likes: 40,
    comments: 6,
    shares: 4,
    following: false,
  },
];

export async function GET() {
  return NextResponse.json(posts);
}
